# Site settings
author: Roshanak Agahi
title: RoshNotes
header-img: img/home-bg.png
email: rosh.agahi@gmail.com
copyright_name: Roshanak Agahi
description: > # this means to ignore newlines until "baseurl:"
  Decrypting the Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rosh-agahi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
